### ISSUE TITLE
Add benchmarks for the time formatting

### ISSUE THREAD

**Issue by ChShersh** [andrewthad/chronos#22]
I see that there're benchmarks for time parsing. And I would really appreciate benchmarks for pretty-printing as well! I assume that some functions can be used for this.

* https://hackage.haskell.org/package/chronos-1.0.4/docs/Chronos.html#g:12

Currently I have non-default time formatter using `time` library but it's known that `time` library is not the fastest one:

```haskell
    showTime :: UTCTime -> Text
    showTime t = toText $
          formatTime defaultTimeLocale "%H:%M:%S." t
       ++ take 3 (formatTime defaultTimeLocale "%q" t)
       ++ formatTime defaultTimeLocale " %e %b %Y %Z" t
```

I would really appreciate to see benchmarks of different libraries!

P.S. You probably can add `Hacktoberfest` label to this issue so some people can implement it. I think that such benchmarks are extremely useful for the Haskell ecosystem.

**Comment by chessai** [comment]
Didnt know what Hacktoberfest was; sounds kinda cool. I think this is worth doing.

**Comment by nobrakal** [comment]
Just took a look at this, and I have a question: 

`formatTime` in `time` and `thyme` return a `String`, but I only see `Builder` producers in `Chronos`, so doing a direct benchmark here is maybe not the best idea, since the returned datatype is not the same.

Can we evaluate the `IO` action of printing a time ? This is "fair" since the input (a time) and the output (an equivalent `IO` action) are equivalent. But it is "unfair" since we take into account how the two `putStr` are implemented for `String` and `Text`...

**Comment by andrewthad** [comment]
Checking the amount of time it takes to print would be bad since printing to the console is somewhat expensive (you have to take a lock). But you're thinking in the right direction. The most fair way to do this would be to fully evaluate both to normal form. For `String`, this is easy. We have the tools from `Control.Deepseq` at our disposal. For bytestring `Builder`, it's a little trickier. You have to convert the `Builder` to a lazy `ByteString` using `toLazyByteString`, and then you can use things from `Control.Deepseq`.
